config/routes.rb
# Auto-generated Routes file was editted by me to create the root directory
# This ensures user is presented with 'welcome#home' as the homepage
# Also ensures the :potatoes table from the database is used in this project

# Author: Ash-Lee Hommy 040840815
# Nov 1st, 2017

Rails.application.routes.draw do
  get 'welcome/home'

  # setting root ensures the app opens to the 'home' page first (tells rails the homepage)
  root 'welcome#home'
  root 'potatoes#index'
  
  resources :potatoes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potato.rb
# Potato model is an Active Record model
# As the db model was created via a rails command, this file is only for changes to default conventions
# :access is a String within the database, which will be serialized to and from an Array when implemented

# Author: Ash-Lee Hommy 040840815
# Nov 1st, 2017

class Potato < ApplicationRecord
  
  # converts to and from an array when storing the record
  serialize :access, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def gallery
    
  end
end

app/controllers/potatoes_controller.rb
# PotatoesController class recieves request (via routing)
# Each method definition (action) makes data available to the potato view, saves/updates to the potato model or routes to a new page
# The 'Potatoes' paths are the main routing path for this project

# Author: Ash-Lee Hommy 040840815
# Nov 1st, 2017

class PotatoesController < ApplicationController
  
  # Index action will be used for the Potato Gallery
  # User is not directly routed to the index yet
  # Current implementation: prints all objects and their attributes within the Potatoes database to the console and index page
  def index
    # this is a list of all the Potatoes in the database
    @all_potatoes = Potato.all
    
    # iterate through each potato in the database and show in console
    @all_potatoes.each do |potato|
      puts "Name: #{potato.name}"
      puts "Description: #{potato.desc}"
      puts "Body: #{potato.body}"
      puts "Mouth: #{potato.mouth}"
      puts "Eyes: #{potato.eyes}"
    end
  end
  
  # Show action
  # After creation of a new random Potato, the ID is passed in
  # Sets the value of the potato from the database and passes to view to display
  def show
    # rails passes all instance variables to the view
    # @potato holds a certain Potato from the database based on the ID primary key
    @potato = Potato.find(params[:id])
  end
  
  # New action
  # Not currently implemented
  def new
    
  end
  
  # Create action
  # Facilitates creation of a new Potato in the database, passing in params from helper method
  # Redirects user to new potato page (Show action)
  def create
    # creates a new Potato and saves all params to the database
    @potato = Potato.create(potato_params)
    
    @potato.save # returns a boolean indicating whether potato was saved or not
    redirect_to @potato
  end
  
  # Private helper method: potato_params
  # Defines the data accepted as params in the potato form
  private
    def potato_params
      # passes parameters to the database columns
      params.require(:potato).permit(:name, :desc, :body, :eyes, :mouth)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/potatoes_helper.rb
module PotatoesHelper

  

# Rails “helpers” are very specifically view helpers. 
#They’re automatically included in views, but not in controllers or models. 
#That’s on purpose.

#Code in the application helper is included in all the views in your application. 
#Code in other helpers is included in the corresponding view. 
#If you find yourself writing big loops, method calls or 
#other logic in the view but it’s clearly display logic, move it into a method 
#in the helper.
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dailypotato</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/potatoes/index.html.erb
<!-- 
	Index.html.erb
	
	This is not fully implemented - will be a Gallery of all the potatoes in the database
	Right now it is passed the variable "@all_potatoes" from the controller which holds every row in the Potatoes database table
	
	Simply prints the value of each Potato to the screen
	
	Author: Ash-Lee Hommy 040840815
	Nov 1st, 2017	
	
	-->
<% @all_potatoes.each do |potato| %>
    Name: <%= potato.name %> <br>
    Description: <%= potato.desc %> <br>
    Body: <%= potato.body %> <br>
    Mouth: <%= potato.mouth %> <br>
    Eyes: <%= potato.eyes %> <br>
    <p>   
<% end %>

app/views/potatoes/new.html.erb
<!-- 
	New.html.erb
	
	View for the New action from potato controller
	User is routed to this page after clicking the "Grant me this day my Daily Potato" button
	
	A new PotatoCreator is created which reads from the CSV file and randomly generates attributes for the potato
	The potato is displayed to the user 
	The user enters a Name and Description and clicks "Submit" to save the Potato to the database
	User is routed to potatoes/show.html.erb
	
	Author: Ash-Lee Hommy 040840815
	Nov 1st, 2017	
	
	-->

<% require 'PotatoCreator'%>
<% require 'PotatoDetail' %>

<h1>New Potato</h1>

<!-- 
	Create a new random potato in ERB
	Creates a new PotatoCreator, which reads from CSV file and sets 
	attributes of new PotatoDetail.
	These attributes are used to set the image attributes of the potato
	-->
<% creator = PotatoCreator.new %>
<% creator.create_potato %>
<% potato = creator.potato %>
<% body = potato.body %>
<% mouth = potato.mouth %>
<% eyes = potato.eyes %>

<!-- 
	Image tags for the potato's body, eyes and mouth
	-->
<%= image_tag("body/#{body}.png", alt: 'potato body', size: "442x598", id: 'body') %>
<%= image_tag("eyes/#{eyes}.png", alt: 'potato eyes', size: "372x127", id: 'eyes') %>
<%= image_tag("mouth/#{mouth}.png", alt: 'potato mouth', size: "320x266", id: 'mouth') %>

<!-- 
	Form for the user to enter the potato's Name and Description
	
	These attributes are sent via parameters to the Show action when user presses Submit
	-->
<%= form_with scope: :potato, url: potatoes_path, local: true do |form| %>
  
  <%= form.hidden_field :body, :value => body %>
  <%= form.hidden_field :mouth, :value => mouth %>
  <%= form.hidden_field :eyes, :value => eyes %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :desc %>
  </p>
 	
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/potatoes/show.html.erb
<!-- 
	Show.html.erb
	
	View for the Show action from potato controller
	User is routed to this page after clicking Submit on the New Potato form
	
	User is routed here to view the Name and Description of their new Potato
	User is routed to welcome/home after clicking Cancel
	
	A new feature will be for the user to See Gallery to view all potatoes
	
	Author: Ash-Lee Hommy 040840815
	Nov 1st, 2017	
	
	-->
<p>
	
<div class="potatoes-wrapper row">
  <div class="potato">
    <div class="potato-head">
      <div class="name">
        <td>Name: <%= @potato.name %></td><br> <!-- Display the name of the potato -->
      </div>
    </div>
    <div class="image center-block">
    	
<!-- Get the attributes from the saved potato in ERB --> 	
<% body = @potato.body %>
<% eyes = @potato.eyes %>
<% mouth = @potato.mouth %>

<!-- Use the above attributes to set the images for the potato -->
<%= image_tag("body/#{body}.png", alt: 'potato body', size: "442x598", id: 'body') %>
<%= image_tag("eyes/#{eyes}.png", alt: 'potato eyes', size: "372x127", id: 'eyes') %>
<%= image_tag("mouth/#{mouth}.png", alt: 'potato mouth', size: "320x266", id: 'mouth') %>
     
<!-- Display the description and allow user to navigate Home using the Cancel hyperlink -->  
    </div>
    <p class="desc">
      Description: <%= @potato.desc %>
    </p>
    <div class="text-center">
      <%= link_to "Cancel", welcome_home_path %>
    </div>
  </div>
</div>

app/views/welcome/home.html.erb
<!-- 
	Home.html.erb
	
	This is the Home page, the first page the user is displayed
	User clicks a button (a trumpet at the moment) "Grant me this day my daily potato"
	User is routed to new.html.erb and displayed a random potato
	
	Author: Ash-Lee Hommy 040840815
	Nov 1st, 2017	
	
	-->
<html>
<body>
	
<center><div id="button">Grant me this day my DAILY POTATO</div></center>

<p></p>

<!-- Trumpet routes user to create a new potato -->
<%= link_to image_tag("trumpet.png", :alt => "trumpet"), new_potato_path %>

</body>
</html>